### ISSUE TITLE
Is this sample still working?

### ISSUE THREAD

**Issue by rogeru** [webrtc-uwp/PeerCC-Sample#1]
Hi, since this example has been updated to webrtc lib v1.58.0.2 I am not able to hear or see the peer media. I am using the server in https://github.com/webrtc-uwp/PeerCC-Sample/tree/master/Server.

On the server console it shows:
```
Disconnecting socket
Total connected:2
New connection ...
```
over and over.

Earlier versions had been working fine.

**Comment by jamescadd** [comment]
Hi @rogeru ,

Please check out the latest M62 version of the sample on the main repo:
https://github.com/webrtc-uwp/PeerCC-Sample/tree/webrtc_merge_m62

This is working for me.  I'll update the samples here in the next day or two.  Let me know if you have any further issues.

Thanks,
James
